name: Generate Snake Animation

# Controls when the action will run
on:
  # Triggers the workflow every 4 hours
  schedule:
    - cron: "0 */4 * * *"

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

  # Triggers the workflow on push to main branch
  push:
    branches: [main]

jobs:
  generate:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      # Checks repo under $GITHUB_WORKSPACE, so the job can access it
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      # Generates the snake
      - name: Generate Snake Animation
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: Nischay23
          outputs: |
            dist/github-contribution-grid-snake.svg
            dist/github-contribution-grid-snake-dark.svg?palette=github-dark&color_snake=#00F5FF&color_dots=#0A1931,#185ADB,#00F5FF,#3498DB,#5352ED

      # Push the content of <build_dir> to a branch
      - name: Push Snake Animation
        uses: crazy-max/ghaction-github-pages@v3
        with:
          target_branch: output
          build_dir: dist
          commit_message: "🐍 Generate Contribution Snake"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
